name: Sync Fork All Branches

on:
  schedule:
    - cron: '0 0 * * *'   # æ¯å¤© 0 ç‚¹è‡ªåŠ¨è¿è¡Œ
  workflow_dispatch:       # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/GameFrameX/GameFrameX.Unity.git
          git fetch upstream --prune

      - name: Sync all branches
        run: |
          for branch in $(git branch -r | grep "upstream/" | sed 's/upstream\///'); do
            echo "ğŸ”„ Syncing branch: $branch"
            git checkout -B $branch upstream/$branch
            git push origin $branch --force
          done
